import { type ILocationGcsCreate, type ILocationGcsCreateResolve, type ILocationGcsDelete, type ILocationGcsDeleteResolve, type ILocationGcsRead, type ILocationGcsReadList, type ILocationGcsReadListResolve, type ILocationGcsReadResolve, type ILocationGcsUpdate, type ILocationGcsUpdateResolve, type ILogErrorCreate, type ILogErrorCreateResolve, type ILogErrorDelete, type ILogErrorDeleteResolve, type ILogErrorRead, type ILogErrorReadList, type ILogErrorReadListResolve, type ILogErrorReadResolve, type ILogErrorUpdate, type ILogErrorUpdateResolve, type IMediaImageCreate, type IMediaImageCreateResolve, type IMediaImageDelete, type IMediaImageDeleteResolve, type IMediaImageRead, type IMediaImageReadList, type IMediaImageReadListResolve, type IMediaImageReadResolve, type IMediaImageUpdate, type IMediaImageUpdateResolve, type INostrProfileCreate, type INostrProfileCreateResolve, type INostrProfileDelete, type INostrProfileDeleteResolve, type INostrProfileRead, type INostrProfileReadList, type INostrProfileReadListResolve, type INostrProfileReadResolve, type INostrProfileUpdate, type INostrProfileUpdateResolve, type INostrRelayCreate, type INostrRelayCreateResolve, type INostrRelayDelete, type INostrRelayDeleteResolve, type INostrRelayRead, type INostrRelayReadList, type INostrRelayReadListResolve, type INostrRelayReadResolve, type INostrRelayUpdate, type INostrRelayUpdateResolve, type ITradeProductCreate, type ITradeProductCreateResolve, type ITradeProductDelete, type ITradeProductDeleteResolve, type ITradeProductRead, type ITradeProductReadList, type ITradeProductReadListResolve, type ITradeProductReadResolve, type ITradeProductUpdate, type ITradeProductUpdateResolve } from "@radroots/models";
import type { IClientDatabase } from "@radroots/util";

export type IClientTauriDatabaseMessage =
    | string
    | "*-fields"
    | "*-result";

export type IClientTauriDatabase = IClientDatabase<
    ILocationGcsCreate,
    ILocationGcsCreateResolve<IClientTauriDatabaseMessage>,
    ILocationGcsRead,
    ILocationGcsReadResolve<IClientTauriDatabaseMessage>,
    ILocationGcsReadList,
    ILocationGcsReadListResolve<IClientTauriDatabaseMessage>,
    ILocationGcsDelete,
    ILocationGcsDeleteResolve<IClientTauriDatabaseMessage>,
    ILocationGcsUpdate,
    ILocationGcsUpdateResolve<IClientTauriDatabaseMessage>,
    ITradeProductCreate,
    ITradeProductCreateResolve<IClientTauriDatabaseMessage>,
    ITradeProductRead,
    ITradeProductReadResolve<IClientTauriDatabaseMessage>,
    ITradeProductReadList,
    ITradeProductReadListResolve<IClientTauriDatabaseMessage>,
    ITradeProductDelete,
    ITradeProductDeleteResolve<IClientTauriDatabaseMessage>,
    ITradeProductUpdate,
    ITradeProductUpdateResolve<IClientTauriDatabaseMessage>,
    INostrProfileCreate,
    INostrProfileCreateResolve<IClientTauriDatabaseMessage>,
    INostrProfileRead,
    INostrProfileReadResolve<IClientTauriDatabaseMessage>,
    INostrProfileReadList,
    INostrProfileReadListResolve<IClientTauriDatabaseMessage>,
    INostrProfileDelete,
    INostrProfileDeleteResolve<IClientTauriDatabaseMessage>,
    INostrProfileUpdate,
    INostrProfileUpdateResolve<IClientTauriDatabaseMessage>,
    INostrRelayCreate,
    INostrRelayCreateResolve<IClientTauriDatabaseMessage>,
    INostrRelayRead,
    INostrRelayReadResolve<IClientTauriDatabaseMessage>,
    INostrRelayReadList,
    INostrRelayReadListResolve<IClientTauriDatabaseMessage>,
    INostrRelayDelete,
    INostrRelayDeleteResolve<IClientTauriDatabaseMessage>,
    INostrRelayUpdate,
    INostrRelayUpdateResolve<IClientTauriDatabaseMessage>,
    IMediaImageCreate,
    IMediaImageCreateResolve<IClientTauriDatabaseMessage>,
    IMediaImageRead,
    IMediaImageReadResolve<IClientTauriDatabaseMessage>,
    IMediaImageReadList,
    IMediaImageReadListResolve<IClientTauriDatabaseMessage>,
    IMediaImageDelete,
    IMediaImageDeleteResolve<IClientTauriDatabaseMessage>,
    IMediaImageUpdate,
    IMediaImageUpdateResolve<IClientTauriDatabaseMessage>,
    ILogErrorCreate,
    ILogErrorCreateResolve<IClientTauriDatabaseMessage>,
    ILogErrorRead,
    ILogErrorReadResolve<IClientTauriDatabaseMessage>,
    ILogErrorReadList,
    ILogErrorReadListResolve<IClientTauriDatabaseMessage>,
    ILogErrorDelete,
    ILogErrorDeleteResolve<IClientTauriDatabaseMessage>,
    ILogErrorUpdate,
    ILogErrorUpdateResolve<IClientTauriDatabaseMessage>
>;
